# -*- coding: utf-8 -*-
"""Chatbot_script2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RIiY44caMUAtSO7j0vddZUsI_J2aU-A4

# DOCUMENTATION
This documentation provides a brief guide on setting up and implementing a basic interactive bot using the OpenAI GPT-4 framework. The bot greets users, asks for their name, email, and company, and stores this information in a simple in-memory structure (a Python dictionary).

Prerequisites
Python 3.x installed on your system.
An OpenAI API key. If you don't have one, sign up at OpenAI and generate an API key.

# STEP-1
Install OpenAI Python Library
"""

pip install openai

"""# STEP-2

Python Script
"""

import openai

# OpenAI API key
api_key = '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'
openai.api_key = api_key

# Function to interact with the bot
def get_response(prompt):
    response = openai.Completion.create(
        engine="text-davinci-003",
        prompt=prompt,
        max_tokens=100,
        n=1,
        stop=None,
        temperature=0.5,
    )
    return response.choices[0].text.strip()

# Main conversation flow
def main():
    user_data = {}

    # Greet User
    print("Bot: Hello! Welcome to our service.")

    # Ask for Name
    user_data['name'] = input("Bot: May I have your name, please?\nYou: ")

    # Ask for Email
    user_data['email'] = input(f"Bot: Thank you, {user_data['name']}. Can you provide your email address?\nYou: ")

    # Ask for Company
    user_data['company'] = input(f"Bot: Great! Which company are you associated with?\nYou: ")

    # Confirmation
    print(f"Bot: Thank you for the information, {user_data['name']}. You are now registered with the email {user_data['email']} and company {user_data['company']}. Have a great day!")

if __name__ == "__main__":
    main()

"""# STEP-3
Initialize Dictionary
"""

user_data = {}

"""# STEP-4
Store User Inputs in Dictionary:
"""

user_data['name'] = input("Bot: May I have your name, please?\nYou: ")
user_data['email'] = input(f"Bot: Thank you, {user_data['name']}. Can you provide your email address?\nYou: ")
user_data['company'] = input(f"Bot: Great! Which company are you associated with?\nYou: ")

"""# STEP-5
Print Collected Data:
"""

print("\nCollected User Data:")
for key, value in user_data.items():
    print(f"{key}: {value}")