# -*- coding: utf-8 -*-
"""oops.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12sdvEDFQ6oAagTbc7T9YJ_6H9kZfKcvJ
"""

class Atm:

  # Constructor
  def __init__(self):
    self.pin=""
    self.balance = 0
    self.menu()

  def menu(self):
    user_input=input("""Hello, how would you like to proceed?
                        1.Enter 1 to creat pin
                        2.Enter 2 to deposit
                        3.Enter 3 to withdraw
                        4.Enter 4 to check balance
                        5.Enter 5 to Exit
                      """)
    if user_input=="1":
      self.create_pin()
    elif user_input=="2":
      self.deposit()
    elif user_input=="3":
      self.withdraw()
    elif user_input=="4":
      self.check_balance()
    else:
      print("Exit")

  def create_pin(self):
    self.pin=input("Enter your pin: ")
    print("Pin set successfully.")

  def deposit(self):
    temp=input("Enter your pin: ")
    if temp==self.pin:
      amount=int(input("Enter the amount: "))
      self.balance = self.balance + amount
      print("Deposit successful.")
    else:
      print("Invalid Pin!")

  def withdraw(self):
    temp=input("Enter your pin: ")
    if temp==self.pin:
      amount=int(input("Enter the amount: "))
      if amount < self.balance:
        self.balance = self.balance - amount
      print("Withdraw successful.")
    else:
      print("Invalid Pin!")

  def check_balance(self):
    temp=input("Enter your pin: ")
    if temp==self.pin:
      print(self.balance)
    else:
      print("Invalid Pin!")

sbi=Atm()
sbi.menu()

sbi.balance

sbi.menu()

sbi.balance

class Customer:

  # Constructor
    def __init__(self,name,gender):
      self.name=name
      self.gender=gender
def greet(customer):
  if customer.gender=="male":
   print("hello", customer.name,"sir")
  else:
      print("female")

cust=Customer("aditya")
cust.name

class Customer:
  def __init__(self,name,gender,address):
    self.name=name
    self.gender=gender
    self.address=address

class Address:
    def __init__(self,city,pincode,state):
      self.city=city
      self.pincode=pincode
      self.state=state

add=Address("palam",110075,"Delhi")
cust=Customer("aditya","male",add)
print(f"Name: {cust.name}, City: {cust.address.city}")

